/**
 * Türkiye İl ve İlçe Verileri
 * Ödeme formlarında dropdown olarak kullanılır
 */
export const TURKEY_CITIES: Record<string, string[]> = {
  "Adana": ["Seyhan", "Yüreğir", "Çukurova", "Sarıçam", "Karaisalı", "Ceyhan", "Kozan", "İmamoğlu", "Pozantı", "Aladağ", "Feke", "Saimbeyli", "Tufanbeyli", "Yumurtalık", "Karataş"],
  "Adıyaman": ["Merkez", "Besni", "Kahta", "Gölbaşı", "Gerger", "Samsat", "Çelikhan", "Sincik", "Tut"],
  "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ", "Çay", "Sultandağı", "Sinanpaşa", "İhsaniye", "Şuhut"],
  "Ağrı": ["Merkez", "Doğubayazıt", "Patnos", "Eleşkirt", "Diyadin", "Tutak", "Hamur", "Taşlıçay"],
  "Aksaray": ["Merkez", "Ortaköy", "Güzelyurt", "Ağaçören", "Eskil", "Gülağaç", "Sarıyahşi", "Sultanhanı"],
  "Amasya": ["Merkez", "Merzifon", "Suluova", "Taşova", "Göynücek", "Gümüşhacıköy", "Hamamözü"],
  "Ankara": ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı", "Çubuk", "Beypazarı", "Polatlı", "Haymana", "Şereflikoçhisar", "Kızılcahamam", "Nallıhan", "Bala", "Elmadağ", "Kalecik", "Kazan", "Akyurt", "Evren", "Güdül", "Ayaş"],
  "Antalya": ["Muratpaşa", "Konyaaltı", "Kepez", "Aksu", "Döşemealtı", "Alanya", "Manavgat", "Serik", "Kumluca", "Kaş", "Kemer", "Finike", "Gazipaşa", "Demre", "Elmalı", "Korkuteli", "Akseki", "Gündoğmuş", "İbradi"],
  "Artvin": ["Merkez", "Arhavi", "Borçka", "Hopa", "Şavşat", "Ardanuç", "Yusufeli", "Murgul"],
  "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "Çine", "Germencik", "İncirliova", "Sultanhisar", "Buharkent", "Karacasu", "Koçarlı", "Kuyucak", "Yenipazar", "Bozdoğan", "Karpuzlu"],
  "Balıkesir": ["Altıeylül", "Karesi", "Bandırma", "Edremit", "Gönen", "Burhaniye", "Ayvalık", "Susurluk", "Bigadiç", "Dursunbey", "Erdek", "Havran", "İvrindi", "Kepsut", "Manyas", "Savaştepe", "Sındırgı", "Marmara", "Balya"],
  "Bartın": ["Merkez", "Ulus", "Kurucaşile", "Amasra"],
  "Batman": ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"],
  "Bayburt": ["Merkez", "Aydıntepe", "Demirözü"],
  "Bilecik": ["Merkez", "Bozüyük", "Osmaneli", "Söğüt", "Gölpazarı", "Pazaryeri", "İnhisar", "Yenipazar"],
  "Bingöl": ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yayladere", "Yedisu"],
  "Bitlis": ["Merkez", "Tatvan", "Ahlat", "Güroymak", "Hizan", "Adilcevaz", "Mutki"],
  "Bolu": ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen", "Dörtdivan", "Kıbrıscık", "Seben", "Yeniçağa"],
  "Burdur": ["Merkez", "Bucak", "Yeşilova", "Gölhisar", "Ağlasun", "Çavdır", "Çeltikçi", "Altınyayla", "Karamanlı", "Kemer", "Tefenni"],
  "Bursa": ["Osmangazi", "Yıldırım", "Nilüfer", "İnegöl", "Gemlik", "Mudanya", "Gürsu", "Kestel", "Karacabey", "Orhangazi", "Mustafakemalpaşa", "İznik", "Yenişehir", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu", "Bayramiç", "Ezine", "Ayvacık", "Yenice", "Lapseki", "Gökçeada", "Bozcaada", "Eceabat"],
  "Çankırı": ["Merkez", "Çerkeş", "Ilgaz", "Kurşunlu", "Şabanözü", "Eldivan", "Yapraklı", "Atkaracalar", "Bayramören", "Kızılırmak", "Korgun", "Orta"],
  "Çorum": ["Merkez", "Sungurlu", "Osmancık", "Alaca", "İskilip", "Bayat", "Kargı", "Mecitözü", "Ortaköy", "Dodurga", "Laçin", "Oğuzlar", "Uğurludağ", "Boğazkale"],
  "Denizli": ["Merkezefendi", "Pamukkale", "Çivril", "Acıpayam", "Tavas", "Buldan", "Sarayköy", "Kale", "Çal", "Honaz", "Serinhisar", "Güney", "Bozkurt", "Çardak", "Baklan", "Beyağaç", "Babadağ", "Bekilli"],
  "Diyarbakır": ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Bismil", "Ergani", "Silvan", "Çermik", "Dicle", "Hani", "Kulp", "Lice", "Kocaköy", "Eğil", "Hazro", "Çınar", "Çüngüş"],
  "Düzce": ["Merkez", "Akçakoca", "Cumayeri", "Gölyaka", "Çilimli", "Gümüşova", "Kaynaşlı", "Yığılca"],
  "Edirne": ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Enez", "Süloğlu", "Meriç", "Lalapaşa"],
  "Elazığ": ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Maden", "Baskil", "Sivrice", "Arıcak", "Keban", "Ağın", "Alacakaya"],
  "Erzincan": ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "Refahiye", "İliç", "Kemah", "Kemaliye", "Otlukbeli"],
  "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Pasinler", "Oltu", "Hınıs", "Aşkale", "Karayazı", "Tekman", "Şenkaya", "İspir", "Tortum", "Narman", "Çat", "Karaçoban", "Köprüköy", "Olur", "Pazaryolu", "Uzundere"],
  "Eskişehir": ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler", "Mahmudiye", "Alpu", "Beylikova", "İnönü", "Sarıcakaya", "Seyitgazi", "Günyüzü", "Han", "Mihalıççık", "Mihalgazi"],
  "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Oğuzeli", "Araban", "Yavuzeli", "Karkamış"],
  "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Keşap", "Piraziz", "Dereli", "Yağlıdere", "Alucra", "Şebinkarahisar", "Güce", "Çamoluk", "Çanakçı", "Doğankent"],
  "Gümüşhane": ["Merkez", "Kelkit", "Şiran", "Torul", "Köse", "Kürtün"],
  "Hakkari": ["Merkez", "Yüksekova", "Şemdinli", "Çukurca"],
  "Hatay": ["Antakya", "İskenderun", "Defne", "Samandağ", "Dörtyol", "Kırıkhan", "Reyhanlı", "Altınözü", "Arsuz", "Belen", "Erzin", "Hassa", "Kumlu", "Payas", "Yayladağı"],
  "Iğdır": ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"],
  "Isparta": ["Merkez", "Yalvaç", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Senirkent", "Keçiborlu", "Sütçüler", "Atabey", "Gönen", "Aksu", "Uluborlu", "Yenişarbademli"],
  "İstanbul": ["Kadıköy", "Beşiktaş", "Üsküdar", "Bakırköy", "Fatih", "Beyoğlu", "Şişli", "Ataşehir", "Maltepe", "Kartal", "Pendik", "Tuzla", "Ümraniye", "Sancaktepe", "Sultanbeyli", "Çekmeköy", "Beykoz", "Adalar", "Sarıyer", "Eyüpsultan", "Gaziosmanpaşa", "Bayrampaşa", "Kağıthane", "Esenler", "Güngören", "Bağcılar", "Bahçelievler", "Zeytinburnu", "Küçükçekmece", "Başakşehir", "Avcılar", "Esenyurt", "Beylikdüzü", "Büyükçekmece", "Çatalca", "Silivri", "Arnavutköy", "Sultangazi", "Sultanahmet"],
  "İzmir": ["Konak", "Karşıyaka", "Bornova", "Buca", "Bayraklı", "Çiğli", "Gaziemir", "Karabağlar", "Balçova", "Narlıdere", "Güzelbahçe", "Menemen", "Torbalı", "Ödemiş", "Bergama", "Tire", "Kemalpaşa", "Aliağa", "Seferihisar", "Urla", "Çeşme", "Foça", "Dikili", "Kiraz", "Selçuk", "Bayındır", "Beydağ", "Karaburun", "Menderes"],
  "Kahramanmaraş": ["Dulkadiroğlu", "Onikişubat", "Elbistan", "Afşin", "Türkoğlu", "Göksun", "Pazarcık", "Andırın", "Çağlayancerit", "Ekinözü", "Nurhak"],
  "Karabük": ["Merkez", "Safranbolu", "Eskipazar", "Yenice", "Ovacık", "Eflani"],
  "Karaman": ["Merkez", "Ermenek", "Sarıveliler", "Kazımkarabekir", "Ayrancı", "Başyayla"],
  "Kars": ["Merkez", "Sarıkamış", "Kağızman", "Selim", "Arpaçay", "Digor", "Susuz", "Akyaka"],
  "Kastamonu": ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Araç", "Cide", "Daday", "Devrekani", "Çatalzeytin", "Abana", "Azdavay", "Bozkurt", "Hanönü", "İhsangazi", "Küre", "Pınarbaşı", "Seydiler", "Şenpazar", "Doğanyurt"],
  "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan", "Tomarza", "Sarıoğlan", "Pınarbaşı", "Yeşilhisar", "Akkışla", "Felahiye", "Hacılar", "İncesu", "Özvatan", "Sarız"],
  "Kırıkkale": ["Merkez", "Delice", "Keskin", "Sulakyurt", "Bahşılı", "Balışeyh", "Çelebi", "Karakeçili", "Yahşihan"],
  "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Kofçaz", "Pehlivanköy"],
  "Kırşehir": ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Akçakent", "Boztepe"],
  "Kilis": ["Merkez", "Musabeyli", "Elbeyli", "Polateli"],
  "Kocaeli": ["İzmit", "Gebze", "Darıca", "Körfez", "Gölcük", "Derince", "Çayırova", "Başiskele", "Dilovası", "Kandıra", "Kartepe", "Karamürsel"],
  "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Seydişehir", "Cihanbeyli", "Kulu", "Sarayönü", "Ilgın", "Çumra", "Kadınhanı", "Bozkır", "Doğanhisar", "Hüyük", "Güneysınır", "Altınekin", "Derebucak", "Emirgazi", "Hadim", "Halkapınar", "Karapınar", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Ahırlı", "Derbent"],
  "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Domaniç", "Altıntaş", "Aslanapa", "Çavdarhisar", "Dumlupınar", "Hisarcık", "Pazarlar", "Şaphane"],
  "Malatya": ["Battalgazi", "Yeşilyurt", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Arguvan", "Arapgir", "Pütürge", "Yazıhan", "Doğanyol", "Kale", "Kuluncak"],
  "Manisa": ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Sarıgöl", "Kula", "Demirci", "Gördes", "Kırkağaç", "Saruhanlı", "Köprübaşı", "Ahmetli", "Gölmarmara", "Selendi"],
  "Mardin": ["Artuklu", "Kızıltepe", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Ömerli", "Savur", "Dargeçit", "Yeşilli"],
  "Mersin": ["Akdeniz", "Mezitli", "Toroslar", "Yenişehir", "Tarsus", "Silifke", "Erdemli", "Anamur", "Mut", "Gülnar", "Aydıncık", "Bozyazı", "Çamlıyayla"],
  "Muğla": ["Menteşe", "Bodrum", "Fethiye", "Milas", "Marmaris", "Dalaman", "Ortaca", "Datça", "Köyceğiz", "Yatağan", "Ula", "Kavaklidere", "Seydikemer"],
  "Muş": ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"],
  "Nevşehir": ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Hacıbektaş", "Kozaklı", "Derinkuyu", "Acıgöl"],
  "Niğde": ["Merkez", "Bor", "Çiftlik", "Ulukışla", "Altunhisar", "Çamardı"],
  "Ordu": ["Altınordu", "Ünye", "Fatsa", "Perşembe", "Akkuş", "Aybastı", "Çamaş", "Çatalpınar", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Ulubey"],
  "Osmaniye": ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale", "Hasanbeyli", "Sumbas"],
  "Rize": ["Merkez", "Çamlıhemşin", "Ardeşen", "Çayeli", "Fındıklı", "Pazar", "İkizdere", "Güneysu", "Hemşin", "Derepazarı", "İyidere", "Kalkandere"],
  "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Arifiye", "Hendek", "Akyazı", "Geyve", "Sapanca", "Karasu", "Kocaali", "Ferizli", "Söğütlü", "Kaynarca", "Pamukova", "Karapürçek", "Taraklı"],
  "Samsun": ["İlkadım", "Atakum", "Canik", "Tekkeköy", "Bafra", "Çarşamba", "Terme", "Vezirköprü", "Havza", "Kavak", "Ladik", "Salıpazarı", "Yakakent", "Alaçam", "Ayvacık", "Asarcık", "19 Mayıs"],
  "Siirt": ["Merkez", "Kurtalan", "Pervari", "Baykan", "Şirvan", "Eruh", "Tillo"],
  "Sinop": ["Merkez", "Boyabat", "Gerze", "Türkeli", "Ayancık", "Durağan", "Erfelek", "Dikmen", "Saraydüzü"],
  "Sivas": ["Merkez", "Şarkışla", "Yıldızeli", "Zara", "Suşehri", "Gemerek", "Kangal", "Divriği", "Hafik", "Gürün", "Koyulhisar", "Doğanşar", "Gölova", "İmranlı", "Ulaş", "Akıncılar", "Altınyayla"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç", "Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Halfeti", "Harran", "Hilvan"],
  "Şırnak": ["Merkez", "Cizre", "Silopi", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"],
  "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Ergene", "Kapaklı", "Saray", "Hayrabolu", "Malkara", "Muratlı", "Marmaraereğlisi", "Şarköy"],
  "Tokat": ["Merkez", "Turhal", "Erbaa", "Niksar", "Zile", "Reşadiye", "Almus", "Artova", "Başçiftlik", "Pazar", "Sulusaray", "Yeşilyurt"],
  "Trabzon": ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin", "Sürmene", "Beşikdüzü", "Vakfıkebir", "Çarşıbaşı", "Maçka", "Tonya", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Şalpazarı"],
  "Tunceli": ["Merkez", "Pertek", "Çemişgezek", "Hozat", "Mazgirt", "Nazımiye", "Ovacık", "Pülümür"],
  "Uşak": ["Merkez", "Eşme", "Banaz", "Sivaslı", "Karahallı", "Ulubey"],
  "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Çaldıran", "Başkale", "Özalp", "Gevaş", "Gürpınar", "Muradiye", "Saray", "Bahçesaray", "Çatak"],
  "Yalova": ["Merkez", "Çınarcık", "Altınova", "Çiftlikköy", "Termal", "Armutlu"],
  "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan", "Sarıkaya", "Çekerek", "Şefaatli", "Çandır", "Kadışehri", "Saraykent", "Aydıncık", "Çayıralan", "Yenifakılı"],
  "Zonguldak": ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Alaplı", "Gökçebey", "Kilimli", "Kozlu"],
}

export const CITY_NAMES = Object.keys(TURKEY_CITIES).sort((a, b) => a.localeCompare(b, 'tr'))
